#! /bin/bash
for n in {1..3}; do
    dd if=/dev/urandom of=file$( printf %03d "$n" ).bin bs=1 count=$(( RANDOM + 1024 ))
done
    dd if=/dev/urandom of=.env bs=1 count=$(( RANDOM + 1024 ))
    dd if=/dev/urandom of=.env.test bs=1 count=$(( RANDOM + 1024 ))
